---
date: today
engine: jupyter
jupyter: bash
---

## What is BIDS (Brain Imaging Data Structure)?

Many of the best practices we encourage in this handbook revolve around the Brain Imaging Data Structure (BIDS) [@gorgolewski2016].
Neuroimaging research relies on complex multimodal data and different software packages have historically used different naming and organization conventions.
Different labs and different researchers use idiosyncratic conventions—even the same researcher may use different conventions from experiment to experiment.
The goal of [BIDS](https://bids-specification.readthedocs.io/en/stable/) is to create an easy-to-adopt community standard for organizing neuroimaging data.
BIDS facilitates:

- **Data validation**: Data often has "bugs"—just like software.
The [BIDS-Validator](https://github.com/bids-standard/bids-validator) can be used to check the integrity of your BIDS dataset, allowing you to identify potential errors or inconsistencies in the data structure.

- **Collaboration**: By using a standard format, working on data collaboratively within and across labs becomes much easier (no more re-organizing someone else's data).
It also makes it much easier to return to the same dataset years later (your future self will thank you).

- **Data analysis**: The machine-readable format and rich metadata of BIDS allows software packages—such as [fMRIPrep](https://fmriprep.readthedocs.io/) and [MRIQC](https://mriqc.readthedocs.io/en/stable/)—to process BIDS data in an automated fashion.
There is a growing number of software packages—called [BIDS Apps](https://bids-apps.neuroimaging.io/)—that capitalize on BIDS [@gorgolewski2017].

- **Sharing data**: Data sharing is an important element of reproducible science and is encouraged (often enforced!) by many major federal funding agencies (e.g., [NIH](https://grants.nih.gov/grants/policy/data_sharing/), [NSF](https://www.nsf.gov/bfa/dias/policy/dmp.jsp), [ERC](https://erc.europa.eu/managing-project/open-access)).
BIDS allows others to more easily use your data and is the standard used by the [OpenNeuro](https://openneuro.org/) data sharing platform [@poldrack2017].
The workflow in this handbook encourages converting your data to BIDS format as early in the workflow as possible to facilitate reproducibility and save you the energy of retroactively organizing your data at the time of sharing.

Consult the [BIDS Specification](https://bids-specification.readthedocs.io/en/stable/) for detailed documentation on formatting.
If you want to setup a new study using BIDS, check out documentation and scripts for converting raw data to BIDS format.
You can also practice using BIDS with sample datasets.

## Tutorial

## Create a directory for your dataset

Create an empty directory and navigate into it:

```{bash}
mkdir mydataset
cd mydataset
```

Download the data by @nastase2020 from [Zenodo](https://doi.org/10.5281/zenodo.3677089):

::: {.callout-warning title="Download can take ca. 5 Min." appearance="minimal"}
:::

```{bash}
wget https://zenodo.org/record/3677090/files/0219191_mystudy-0219-1114.tar.gz
```

```{bash}
tar -xvzf 0219191_mystudy-0219-1114.tar.gz
```

Let's navigate into the directory and see what's inside the dataset:

```{bash}
tree -L 2 0219191_mystudy-0219-1114
```

```{bash}
gunzip 0219191_mystudy-0219-1114/dcm/*.dcm.gz
```

```{bash}
mkdir bids
heudiconv -f reproin --subject 01 --ses 01 --bids --files 0219191_mystudy-0219-1114/dcm --overwrite
```

## Resources

- [BIDS Specification](https://bids-specification.readthedocs.io/en/stable/)
- [BIDS-Validator](https://github.com/bids-standard/bids-validator)
- [BIDS Apps](https://bids-apps.neuroimaging.io/)
- [OpenNeuro](https://openneuro.org/)
- [fMRIPrep](https://fmriprep.readthedocs.io/)
- [MRIQC](https://mriqc.readthedocs.io/en/stable/)
- [National Institutes of Health (NIH) Data Sharing Policy](https://grants.nih.gov/grants/policy/data_sharing/)
- [National Science Foundation (NSF) Dissemination and Sharing of Research Results](https://www.nsf.gov/bfa/dias/policy/dmp.jsp)
- [European Research Council (ERC) Open Access](https://erc.europa.eu/managing-project/open-access)

## References

:::{#refs}
:::

- Python {{< env QUARTO_PYTHON >}}
- Profile: {{< env QUARTO_PROFILE >}}
